services:
  - type: web
  disks:
    name: buildcache
    env: node
    mountPath: /cache
    buildCommand: mkdir -p /cache/.next/cache && ln -sfn /cache/.next/cache .next/cache && pnpm install && pnpm build
    startCommand: pnpm start
    sizeGB: 1
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
