services:
  - type: web
    env: node
    buildCommand: pnpm install && rm -f next.config.js && pnpm dlx turbo run build
    startCommand: pnpm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
